### ISSUE TITLE
Wrong guzzle version required

### ISSUE THREAD

**Issue by spointecker** [taobig/apple-id-login#1]
Hey,

is it possible that you have the wrong requirement for the guzzlehttp/guzzle package (https://packagist.org/packages/guzzlehttp/guzzle) in your package.json?

Currently:
`"guzzlehttp/guzzle": "^6.3 || ^8.4"`

But the latest version of it is currently `7.4`.

**Comment by taobig** [comment]
@spointecker fixed, please upgrade to v1.1.1.

**Comment by spointecker** [comment]
thanks for the quick fix! @taobig :)
